### ISSUE TITLE
Wrong path for package import

### ISSUE THREAD

**Issue by JChanceHud** [Clarifai/clarifai-javascript#7]
I'm getting this error.
```
[ 'Error: Cannot find module \'./../package.json\'',
     '    at Function.Module._resolveFilename (module.js:472:15)',
     '    at Function.Module._load (module.js:420:25)',
     '    at Module.require (module.js:500:17)',
     '    at require (internal/module.js:20:19)',
     '    at Object.<anonymous> (/Users/Chance/Development/cosmunity/backend/node_modules/clarifai/dist/node/utils.js:15:17)'
```
The path referencing `package.json` is correct in `/src/utils.js`, but is incorrect in `/dist/node/utils.js` because the file is 1 level deeper. I think this was introduced in 080e0ba4e8f92e26583a84ba9d2f6aef4ff52ec8. @zeiler 

This bug breaks any package depending on Clarifai

**Comment by cmisenas** [comment]
@JChanceHud Thanks for reporting this! Resolved with 2.0.11
